import { SectorSummary, DepartmentCluster, OperationalTier } from '@/types/semantic_map.types';

export const INITIAL_SECTORS: SectorSummary[] = [
  {
    id: 'sec-office',
    route: '/office',
    label: 'Spatial Focus Canvas',
    category: 'Execution & Flow',
    description: 'Interactive 2D desk layout, silent focus pods, and localized sticky notes.',
    tier: 1,
    tierName: 'Tier 1: Solitary Deep Work',
    activeCount: 7,
    capacity: 24,
    subContexts: [
      { id: 'sub-eng', name: 'Engineering Desk Cluster', activeCount: 4 },
      { id: 'sub-focus', name: 'Deep-Work Focus Pods', activeCount: 2 },
      { id: 'sub-hot', name: 'Open Hot Desks', activeCount: 1 },
    ],
    occupants: [
      {
        user: {
          id: 'b0000000-0000-0000-0000-000000000001',
          email: 'alex@squad.realnthq.local',
          fullName: 'Alex Vance',
          displayTitle: 'Head of Engineering',
          status: 'AVAILABLE',
          statusMessage: 'Reviewing PRs and architecture',
        },
        department: 'ENGINEERING',
        location: {
          route: '/office',
          subContextId: 'desk-1',
          subContextName: 'Desk ENG-01',
          tier: 1,
          activityLabel: 'Focusing on Core Router',
        },
      },
      {
        user: {
          id: 'u-sarah',
          email: 'sarah@squad.realnthq.local',
          fullName: 'Sarah Connor',
          displayTitle: 'Staff Product Designer',
          status: 'DEEP_WORK',
          statusMessage: 'Design system tokens update',
        },
        department: 'PRODUCT_DESIGN',
        location: {
          route: '/office',
          subContextId: 'desk-2',
          subContextName: 'Desk ENG-02',
          tier: 1,
          activityLabel: 'Deep Work Flow',
        },
      },
      {
        user: {
          id: 'u-kenji',
          email: 'kenji@squad.realnthq.local',
          fullName: 'Kenji Sato',
          displayTitle: 'Distributed Systems Lead',
          status: 'AVAILABLE',
        },
        department: 'ENGINEERING',
        location: {
          route: '/office',
          subContextId: 'desk-3',
          subContextName: 'Desk ENG-03',
          tier: 1,
          activityLabel: 'Writing Consensus Specs',
        },
      },
    ],
  },
  {
    id: 'sec-rooms',
    route: '/rooms',
    label: 'Collaboration Rooms',
    category: 'Synchronous Huddles',
    description: 'Low-latency WebRTC video suites, whiteboards, and incident war rooms.',
    tier: 3,
    tierName: 'Tier 3: Squad Huddles',
    activeCount: 5,
    capacity: 38,
    subContexts: [
      { id: 'sub-turing', name: 'Turing War Room', activeCount: 2 },
      { id: 'sub-coffee', name: 'Virtual Coffee Bar', activeCount: 3 },
      { id: 'sub-lovelace', name: 'Lovelace Sync Hub', activeCount: 0 },
    ],
    occupants: [
      {
        user: {
          id: 'u-marcus',
          email: 'marcus@squad.realnthq.local',
          fullName: 'Marcus Brody',
          displayTitle: 'Site Reliability Engineer',
          status: 'IN_MEETING',
        },
        department: 'ENGINEERING',
        location: {
          route: '/rooms',
          subContextId: 'room-1',
          subContextName: 'Turing War Room',
          tier: 3,
          activityLabel: 'Database Failover Drill',
        },
        isMicActive: true,
      },
      {
        user: {
          id: 'u-elena',
          email: 'elena@squad.realnthq.local',
          fullName: 'Elena Rostova',
          displayTitle: 'Product Operations Lead',
          status: 'IN_MEETING',
        },
        department: 'PRODUCT_DESIGN',
        location: {
          route: '/rooms',
          subContextId: 'room-1',
          subContextName: 'Turing War Room',
          tier: 3,
          activityLabel: 'Active Whiteboarding',
        },
        isScreenSharing: true,
      },
    ],
  },
  {
    id: 'sec-broadcasts',
    route: '/broadcasts',
    label: 'Company Townhall & News',
    category: 'Org-Wide Alignment',
    description: 'Live executive broadcasts, pinned updates, and company news portal.',
    tier: 4,
    tierName: 'Tier 4: Macro All-Hands',
    activeCount: 14,
    capacity: 500,
    subContexts: [
      { id: 'sub-amphi', name: 'Main Amphitheater Stream', activeCount: 11 },
      { id: 'sub-news', name: 'Bulletin Announcement Feed', activeCount: 3 },
    ],
    occupants: [
      {
        user: {
          id: 'u-clara',
          email: 'clara@squad.realnthq.local',
          fullName: 'Clara Oswald',
          displayTitle: 'VP of Operations',
          status: 'AVAILABLE',
        },
        department: 'LEADERSHIP',
        location: {
          route: '/broadcasts',
          subContextId: 'stage-1',
          subContextName: 'Executive Stage',
          tier: 4,
          activityLabel: 'Broadcasting Q3 Roadmap',
        },
        isMicActive: true,
      },
    ],
  },
  {
    id: 'sec-standup',
    route: '/standup',
    label: 'Daily Standup Kiosk',
    category: 'Async Check-ins',
    description: 'Asynchronous updates, yesterday/today progress, and blocker resolution.',
    tier: 1,
    tierName: 'Tier 1: Async Pulse',
    activeCount: 2,
    subContexts: [
      { id: 'sub-active-checkin', name: 'Live Check-in Desk', activeCount: 2 },
    ],
    occupants: [],
  },
  {
    id: 'sec-team',
    route: '/team',
    label: 'Team & Role Directory',
    category: 'People & Taxonomy',
    description: 'Organizational hierarchy, skill taxonomies, and instant desk knock dispatcher.',
    tier: 5,
    tierName: 'Tier 5: Governance & Taxonomy',
    activeCount: 3,
    subContexts: [
      { id: 'sub-eng-dir', name: 'Engineering Roster', activeCount: 2 },
      { id: 'sub-people-dir', name: 'People Ops Registry', activeCount: 1 },
    ],
    occupants: [],
  },
  {
    id: 'sec-artifacts',
    route: '/artifacts',
    label: 'Decision Logs & Memory',
    category: 'Knowledge Repository',
    description: 'Architecture Decision Records (ADRs), post-mortems, and shared sketches.',
    tier: 5,
    tierName: 'Tier 5: Knowledge Base',
    activeCount: 2,
    subContexts: [
      { id: 'sub-adr', name: 'ADR-004 Topology RFC', activeCount: 2 },
    ],
    occupants: [],
  },
];

export const DEPARTMENT_OPTIONS: Array<{ id: DepartmentCluster; label: string }> = [
  { id: 'ALL', label: 'All Departments' },
  { id: 'ENGINEERING', label: 'Engineering' },
  { id: 'PRODUCT_DESIGN', label: 'Product & Design' },
  { id: 'REVENUE', label: 'Revenue & GTM' },
  { id: 'PEOPLE_OPS', label: 'People Ops' },
  { id: 'LEADERSHIP', label: 'Leadership' },
];

export const TIER_DESCRIPTIONS: Record<OperationalTier, { title: string; subtitle: string }> = {
  1: { title: 'Tier 1: Solitary Deep Work', subtitle: 'Focused individual execution at desk with distraction shield' },
  2: { title: 'Tier 2: Micro-Pairing', subtitle: '1-on-1 ad-hoc audio knocks and peer pairing' },
  3: { title: 'Tier 3: Squad Huddles', subtitle: 'Synchronous named war rooms, whiteboards, and audio/video' },
  4: { title: 'Tier 4: Macro All-Hands', subtitle: 'Company-wide townhalls and executive broadcast streams' },
  5: { title: 'Tier 5: Platform Governance', subtitle: 'Org taxonomy, telemetry, and system-wide knowledge' },
};
